spring.application.name=TMS
spring.datasource.url=jdbc:mysql://localhost:3306/TMS
spring.datasource.username=root
spring.datasource.password=Skibidi@26gyatt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true